import PptxGenJS from "pptxgenjs";
import { SlideData, PresentationSettings } from "../types";
import { compressImage } from "./utils";

export const generatePPTX = async (
  slides: SlideData[], 
  settings: PresentationSettings,
  filename: string = "presentation.pptx"
) => {
  const pres = new PptxGenJS();

  // Set Metadata
  pres.author = "Gemini SlideGen";
  pres.company = "AI Generated";
  pres.title = "Image Presentation";

  pres.defineSlideMaster({
    title: "MASTER_SLIDE",
    background: { color: "FFFFFF" },
    objects: [
      { rect: { x: 0, y: "90%", w: "100%", h: "10%", fill: { color: "F1F5F9" } } },
      { text: { text: "Generated by Gemini SlideGen", options: { x: 0.5, y: "92%", w: 5, h: 0.5, fontSize: 10, color: "64748B" } } },
    ],
  });

  for (const slideData of slides) {
    const slide = pres.addSlide({ masterName: "MASTER_SLIDE" });
    
    // Compress and convert file to Data URL to avoid Invalid String Length errors
    const imageDataUrl = await compressImage(slideData.file);
    
    const content = slideData.content;
    const titleText = content?.title || `Slide ${slides.indexOf(slideData) + 1}`;
    const points = content?.points || [];

    // --- Layout Logic ---
    
    if (settings.layout === 'fullscreen') {
        // 1. Full Screen Image
        slide.addImage({
            data: imageDataUrl,
            x: 0,
            y: 0,
            w: "100%",
            h: "100%",
            sizing: { type: "cover", w: "100%", h: "100%" }
        });

        // For fullscreen, if we have text, we typically overlay it
        const hasText = (settings.includeTitle || (settings.includePoints && points.length > 0));
        
        if (hasText) {
            // Add a semi-transparent overlay at the bottom
            slide.addShape(pres.ShapeType.rect, {
                x: 0, y: "65%", w: "100%", h: "25%",
                fill: { color: "000000", transparency: 30 }
            });

            if (settings.includeTitle) {
                slide.addText(titleText, {
                    x: 0.5, y: "66%", w: "90%", h: 0.8,
                    fontSize: 24, bold: true, color: "FFFFFF", fontFace: "Arial"
                });
            }

            if (settings.includePoints && points.length > 0) {
                 const bulletText = points.map(p => ({
                    text: p,
                    options: { breakLine: true, bullet: true, indentLevel: 0 }
                }));
                slide.addText(bulletText, {
                    x: 0.5, y: "75%", w: "90%", h: 2,
                    fontSize: 14, color: "E2E8F0", lineSpacing: 20
                });
            }
        }

    } else if (settings.layout === 'left') {
        // Image Left, Text Right
        
        // Image
        slide.addImage({
            data: imageDataUrl,
            x: 0.5, y: 1, w: 4.5, h: 4.5,
            sizing: { type: "contain", w: 4.5, h: 4.5 }
        });

        // Text Area
        const textX = 5.5;
        
        if (settings.includeTitle) {
            slide.addText(titleText, {
                x: textX, y: 1, w: 4, h: 1,
                fontSize: 24, bold: true, color: "0F172A", fontFace: "Arial"
            });
        }

        if (settings.includePoints && points.length > 0) {
            const bulletText = points.map(p => ({
                text: p,
                options: { breakLine: true, bullet: true, indentLevel: 0 }
            }));
            // Adjust Y based on title presence
            const startY = settings.includeTitle ? 2.2 : 1; 
            slide.addText(bulletText, {
                x: textX, y: startY, w: 4, h: 3,
                fontSize: 16, color: "334155", lineSpacing: 28
            });
        }

    } else if (settings.layout === 'right') {
        // Image Right, Text Left
        
        // Image
        slide.addImage({
            data: imageDataUrl,
            x: 5.5, y: 1, w: 4.5, h: 4.5,
            sizing: { type: "contain", w: 4.5, h: 4.5 }
        });

        // Text Area
        const textX = 0.5;
        
        if (settings.includeTitle) {
            slide.addText(titleText, {
                x: textX, y: 1, w: 4.5, h: 1,
                fontSize: 24, bold: true, color: "0F172A", fontFace: "Arial"
            });
        }

        if (settings.includePoints && points.length > 0) {
             const bulletText = points.map(p => ({
                text: p,
                options: { breakLine: true, bullet: true, indentLevel: 0 }
            }));
            const startY = settings.includeTitle ? 2.2 : 1;
            slide.addText(bulletText, {
                x: textX, y: startY, w: 4.5, h: 3,
                fontSize: 16, color: "334155", lineSpacing: 28
            });
        }
    }
  }

  // Save the file
  await pres.writeFile({ fileName: filename });
};